name: blog

dependencies:
- base >= 4.7 && < 5
- hakyll
- tasty
- tasty-hunit
- blaze-html
- containers
- filepath
- directory
- free
- mtl
- blaze-markup
- polysemy
- extra
- comonad

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

default-extensions:
- OverloadedStrings
- DerivingStrategies
- DeriveFunctor
- DeriveFoldable
- DeriveTraversable

- DataKinds
- FlexibleContexts
- GADTs
- LambdaCase
- PolyKinds
- RankNTypes
- ScopedTypeVariables
- TemplateHaskell
- TypeApplications
- TypeOperators
- TypeFamilies

library:
    source-dirs: src

executables:
    blog-exe:
        main:                Main.hs
        source-dirs:         app
        ghc-options:
        - -threaded
        - -rtsopts
        - -with-rtsopts=-N
        dependencies:
        - blog

tests:
    blog-test:
        main:                Spec.hs
        source-dirs:         test
        ghc-options:
        - -threaded
        - -rtsopts
        - -with-rtsopts=-N
        dependencies:
        - blog
